[ip]
name = "gates"
version = "1.0.1"
channels = ["hyperspace-labs"]
source = "https://github.com/hyperspace-labs/gates/archive/{{orbit.ip.version}}.zip"

# See more keys and their definitions at https://cdotrus.github.io/orbit/reference/manifest.html

[dependencies]
